Fix fails in TestCudaWarpOperations
There are two failures in TestCudaWarpOperations:

```
======================================================================
ERROR: test_independent_scheduling (numba.cuda.tests.cudapy.test_warp_ops.TestCudaWarpOperations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/tests/cudapy/test_warp_ops.py", line 241, in test_independent_scheduling
    self.assertTrue(np.all(ary_out == exp))
NameError: name 'ary_out' is not defined

======================================================================
FAIL: test_match_any_sync (numba.cuda.tests.cudapy.test_warp_ops.TestCudaWarpOperations)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/tests/cudapy/test_warp_ops.py", line 219, in test_match_any_sync
    self.assertTrue(np.all(ary_out == exp))
AssertionError: False is not true

----------------------------------------------------------------------
```

This commit fixes them with these changes:

- test_independent_scheduling overflows an int32 with its output,
  so its argument types are changes to uint32. There is also a
  copy/paste error (probably), where ary_out (which doesn't exist)
  is compared against exp - this commit changes it to arr.
- test_match_any_sync has the values in the expected data
  transposed. This commit switches them round to fix the test. I
  have also checked that the Numba implementation of the intrinsic
  is correct by comparing the output against a similar CUDA C
  program.

This is tested on a Tesla V100-SXM2-16GB; the tests now pass with
this commit.