Better error message if __init__ returns value
Mirrors the behavior of normal Python.

```
>>> import numba
>>> class Test:
...     def __init__(self):
...             return 7
...
>>> Test()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() should return None, not 'int'
>>> jitTest = numba.experimental.jitclass([])(Test)
__main__:1: NumbaDeprecationWarning: The 'numba.jitclass' decorator has moved to 'numba.experimental.jitclass' to better reflect the experimental nature of the functionality. Please update your imports to accommodate this change and see http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#change-of-jitclass-location for the time frame.
>>> jitTest()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ethanpronovost/Documents/Projects/numba/numba/numba/experimental/jitclass/base.py", line 122, in __call__
    return cls._ctor(*bind.args[1:], **bind.kwargs)
  File "/Users/ethanpronovost/Documents/Projects/numba/numba/numba/core/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/ethanpronovost/Documents/Projects/numba/numba/numba/core/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/Users/ethanpronovost/Documents/Projects/numba/numba/numba/core/utils.py", line 79, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.core.typeinfer.CallConstraint object at 0x61ed59cf8>.
__init__() should return None, not 'Literal[int](7)'
[1] During: resolving callee type: jitclass.Test#11daf76d8<>
[2] During: typing of call at <string> (3)

Enable logging at debug level for details.

File "<string>", line 3:
<source missing, REPL/exec in use?>
```