Add tests and fixes
- The simulator implementation of nanmin and nanmax failed to return the
  old value - it now returns them correctly.
- `PTR_OR_VAL` for the `nanmax` and `nanmin` implementations should be
  the empty string so that the resulting implementation doesn't return
  early when the existing value is a NaN.
- Tests for returning the old value added.

All added tests pass in the simulator. With the real device target,
there are two fails:

```
======================================================================
FAIL: test_atomic_nanmax_returns_old_nan_in_array (numba.cuda.tests.cudapy.test_atomics.TestCudaAtomics)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/cuda/tests/cudapy/test_atomics.py", line 703, in test_atomic_nanmax_returns_old_nan_in_array
    self._test_atomic_nan_returns_old(kernel, np.nan)
  File "/home/gmarkall/numbadev/numba/numba/cuda/tests/cudapy/test_atomics.py", line 687, in _test_atomic_nan_returns_old
    self.assertTrue(np.isnan(x[1]))
AssertionError: False is not true

======================================================================
FAIL: test_atomic_nanmin_returns_old_nan_in_array (numba.cuda.tests.cudapy.test_atomics.TestCudaAtomics)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/cuda/tests/cudapy/test_atomics.py", line 724, in test_atomic_nanmin_returns_old_nan_in_array
    self._test_atomic_nan_returns_old(kernel, np.nan)
  File "/home/gmarkall/numbadev/numba/numba/cuda/tests/cudapy/test_atomics.py", line 687, in _test_atomic_nan_returns_old
    self.assertTrue(np.isnan(x[1]))
AssertionError: False is not true
```

This is because the new value gets returned instead of the old when the
initial value is a NaN - the logic in the IR implementations is
incorrect for implementing always returning the old value when the old
value is a NaN.